{if !empty($coupon_blocks.featured_shops)}
	{foreach $coupon_blocks.featured_shops as $featured_shop}
	<div class="featured-shop-item">
			<a href="{ia_url type='url' item='shops' data=$featured_shop}" class="shop-thumbnail">
				{if $featured_shop.shop_image}
					{printImage imgfile=$featured_shop.shop_image.path title=$featured_shop.title|escape:'html' width='125' height='125'}
				{else}
					<img src="http://api.webthumbnail.org?width=125&height=125&format=png&screen=1024&url={$featured_shop.website}" alt="Generated by WebThumbnail.org">
				{/if}
			</a>
			<h5><a href="{ia_url type='url' item='shops' data=$featured_shop}">{$featured_shop.title}</a></h5>
			<p>{$featured_shop.description|strip_tags|truncate:150:'...'}</p>
		</div>
	{/foreach}
{/if}