<div class="media ia-item ia-item-bordered shops-list-item">
    {if $listing.shop_image}
        <a href="{ia_image file=$listing.shop_image url=true type='large'}" class="pull-left ia-item-thumbnail" rel="ia_lightbox">
            {ia_image file=$listing.shop_image type='thumbnail' title=$listing.title class='media-object'}
        </a>
    {else}
        <a href="{ia_url type='url' item='shops' data=$listing}" class="pull-left ia-item-thumbnail">
            <img src="//api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$listing.website}" alt="Generated by WebThumbnail.org" class="media-object">
        </a>
    {/if}

    <div class="media-body">
        <h4 class="media-heading">{ia_url type='link' item='shops' data=$listing text=$listing.title}</h4>
        <div class="ia-item-body">{$listing.description|strip_tags|truncate:200:'...'}</div>
    </div>
</div>