<div class="shop-page clearfix">
    <div class="image pull-left">
        {if !empty($item.shop_image)}
            <a href="{ia_image file=$item.shop_image url=true type='large'}" class="shop-thumb" rel="ia_lightbox">
                {ia_image file=$item.shop_image type='thumbnail' title=$item.title}
            </a>
        {else}
            <a href="{$item.website}" class="shop-thumb" target="_blank">
                <img src="//api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$item.website}" alt="Generated by WebThumbnail.org">
            </a>
        {/if}
    </div>

    <p>
        <b>{lang key='website'}:</b>
        {if $item.affiliate_link && 'http://' != $item.affiliate_link}
            <a href="{$item.affiliate_link}" target="_blank">{$item.website}</a>
        {else}
            <a href="{$item.website}" target="_blank">{$item.website}</a>
        {/if}
    </p>

    {if !empty($item.description)}
        <div class="slogan">{$item.description}</div>
    {/if}

    {ia_hooker name='smartyItemViewBeforeTabs'}

    {include 'item-view-tabs.tpl' isView=true exceptions=['title_en', 'affiliate_link', 'website', 'description_en'] class='ia-item-view-tabs'}
</div>

{ia_hooker name='smartyViewListingBeforeFooter'}

<form>
    <select id="js-sort-options" name='sorting' class='form-control'>
        <option value="all"{if isset($smarty.get.sorting) && 'all' == $smarty.get.sorting} selected{/if}>{lang key='show_all_coupons'}</option>
        <option value="active"{if isset($smarty.get.sorting) && 'active' == $smarty.get.sorting} selected{/if}>{lang key='show_active_coupons'}</option>
        <option value="expired"{if isset($smarty.get.sorting) && 'expired' == $smarty.get.sorting} selected{/if}>{lang key='show_expired_coupons'}</option>
    </select>
</form>
{ia_add_js}
$(function() {
    $('#js-sort-options').on('change', function() {
        $(this).parent().submit();
    });
});
{/ia_add_js}
<hr>
<h3>{lang key='coupons'}: {$coupons|count}</h3>

{if $coupons}
    {foreach $coupons as $listing}
        {include 'extra:coupons/list-coupons'}
    {/foreach}
{else}
    <div class="alert alert-info">{lang key='no_coupons_for_shop'}</div>
{/if}

{if $coupons_expired}
    <h3>{lang key='expired_coupons'}: {$coupons_expired|count}</h3>
    {foreach $coupons_expired as $listing}
        {include 'extra:coupons/list-coupons'}
    {/foreach}
{/if}