{if !empty($coupon_blocks.popular_shops)}
	<div id="popular_shops_slider" class="js-flexslider flexslider">
		<ul class="slides">
			{foreach $coupon_blocks.popular_shops as $popular_shop}
				<li>
					<div class="popular-shop-item">
						<a href="{ia_url type='url' item='shops' data=$popular_shop}" class="shop-thumbnail">
							{if $popular_shop.shop_image}
								{printImage imgfile=$popular_shop.shop_image.path title=$popular_shop.title|escape:'html' width='150' height='150'}
							{else}
								<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$popular_shop.website}" alt="Generated by WebThumbnail.org">
							{/if}
						</a>
						<h5><a href="{ia_url type='url' item='shops' data=$popular_shop}">{$popular_shop.title}</a></h5>
						<p>{$popular_shop.description|strip_tags|truncate:80:'...'}</p>
					</div>
				</li>
			{/foreach}
		</ul>
	</div>

	{ia_add_media files='flexslider'}
	{ia_add_js}
$(window).load(function()
{
	$('.js-flexslider').flexslider(
	{
		animation: "slide",
		pauseOnHover: true,
		itemWidth: 154,
		itemMargin: 0,
		prevText: '',
		nextText: ''
	});
});
	{/ia_add_js}
{/if}