{if isset($shop)}
	<div class="ia-items author-block">
		<div class="media ia-item">
			{if $shop.shop_image}
				<a href="{printImage imgfile=$shop.shop_image.path url=true fullimage=true}" class="thumbnail media-object pull-left" rel="ia_lightbox">
					{printImage imgfile=$shop.shop_image.path title=$shop.title|escape:'html' width=50 height=50}
				</a>
			{else}
				<a href="{$smarty.const.IA_URL}shop/{$shop.title_alias}.html" class="thumbnail media-object pull-left">
					<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$shop.website}" alt="Generated by WebThumbnail.org" width="50" height="50">
				</a>
			{/if}

			<div class="media-body">
				<ul class="unstyled">
					<li>{$shop.title}</li>
					<li>
						<i class="icon-external-link"></i> 
						{if $shop.affiliate_link && 'http://' != $shop.affiliate_link}
							<a href="{$shop.affiliate_link}">{lang key='website'}</a>
						{else}
							<a href="{$shop.website}">{lang key='website'}</a>
						{/if}
					</li>
				</ul>
			</div>

			<table class="table table-condensed table-striped statistics">
				<thead>
					<tr><th colspan="2">{lang key='shop_activity'}</th></tr>
				</thead>
				<tbody>
					<tr>
						<td>{lang key='coupons'}:</td>
						<td>{$shop.num_coupons|string_format:'%d'}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
{/if}