{if $coupon_blocks.oftheday}
	<div class="ia-item">
		<div class="m-b">
			{if $coupon_blocks.oftheday.coupon_image}
				{assign 'imgthumb' $coupon_blocks.oftheday.coupon_image|unserialize}
				<a href="{printImage imgfile=$imgthumb.path url=true fullimage=true}" rel="ia_lightbox" class="center-block">
					{printImage imgfile=$imgthumb.path title=$coupon_blocks.oftheday.title|escape:'html' class='img-responsive'}
				</a>
			{elseif $coupon_blocks.oftheday.shop_image}
				<a href="{printImage imgfile=$coupon_blocks.oftheday.shop_image.path url=true fullimage=true}" rel="ia_lightbox" class="center-block">
					{printImage imgfile=$coupon_blocks.oftheday.shop_image.path title=$coupon_blocks.oftheday.shop_title|escape:'html' class='img-responsive'}
				</a>
			{else}
				<a href="{$smarty.const.IA_URL}shop/{$coupon_blocks.oftheday.shop_alias}.html" class="center-block">
					<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$coupon_blocks.oftheday.shop_website}" alt="Generated by WebThumbnail.org" class="img-responsive">
				</a>
			{/if}
		</div>

		<div class="ia-item__content">
			<div class="ia-item__title">
				{ia_url type='link' item='coupons' data=$coupon_blocks.oftheday text=$coupon_blocks.oftheday.title} <small>{lang key='from'} <a href="{$smarty.const.IA_URL}shop/{$coupon_blocks.oftheday.shop_alias}.html">{$coupon_blocks.oftheday.shop_title}</a></small>
			</div>

			<p>{$coupon_blocks.oftheday.short_description|strip_tags|truncate:150:'...'}</p>
		</div>
	</div>
{/if}