<div id="coupon-list-{$listing.id}" class="media ia-item ia-item-bordered ia-item-coupon{if $listing.featured} ia-item-featured{/if}{if $listing.sponsored} ia-item-sponsored{/if}" data-affiliate-link="{if $listing.affiliate_link && 'http://' != $listing.affiliate_link}{$listing.affiliate_link}{elseif $listing.shop_affiliate_link && 'http://' != $listing.shop_affiliate_link}{$listing.shop_affiliate_link}{/if}">
	{if $listing.featured}
		<span class="ia-badge ia-badge-featured" title="{lang key='featured'}"><i class="icon-star"></i></span>
	{/if}

	{if $listing.sponsored}
		<span class="ia-badge ia-badge-sponsored" title="{lang key='sponsored'}"><i class="icon-dollar"></i></span>
	{/if}

	<div class="pull-left">
		{if $listing.coupon_image}
			{assign 'imgthumb' $listing.coupon_image|unserialize}
			<a href="{printImage imgfile=$imgthumb.path url=true fullimage=true}" class="ia-item-thumbnail" rel="ia_lightbox">
				{printImage imgfile=$imgthumb.path title=$listing.title|escape:'html' class='media-object' width=150}
			</a>
		{elseif $listing.shop_image}
			<a href="{printImage imgfile=$listing.shop_image.path url=true fullimage=true}" class="ia-item-thumbnail" rel="ia_lightbox">
				{printImage imgfile=$listing.shop_image.path title=$listing.shop_title|escape:'html' class='media-object' width=150}
			</a>
		{else}
			<a href="{$smarty.const.IA_URL}shop/{$listing.shop_alias}.html" class="ia-item-thumbnail">
				<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$listing.shop_website}" alt="Generated by WebThumbnail.org" class="media-object">
			</a>
		{/if}

		<div class="coupon-rate text-center">
			<a href="#" class="thumbs-up" data-id="{$listing.id}" data-trigger="up"><i class="fa fa-thumbs-up fa-white"></i></a>
			<span class="rate good" id="thumb_result_{$listing.id}">{$listing.thumbs_num|default:0}</span>
			<a href="#" class="thumbs-down" data-id="{$listing.id}" data-trigger="down"><i class="fa fa-thumbs-down fa-white"></i></a>
		</div>
	</div>

	<div class="media-body">
		<h4 class="media-heading">{ia_url type='link' item='coupons' data=$listing text=$listing.title} <small>{lang key='from'} <a href="{$smarty.const.IA_URL}shop/{$listing.shop_alias}.html">{$listing.shop_title}</a></small></h4>

		{if $listing.item_price && '0.00' != $listing.item_price}
			<div class="coupon-price clearfix">
				{if $listing.item_discount}
					{if 'fixed' == $listing.item_discount_type}
						{assign var=discount_total value=($listing.item_price - $listing.item_discount)}
						{assign discount $listing.item_discount}
					{else}
						{assign var=discount_total value=($listing.item_price - $listing.item_price * $listing.item_discount / 100)}
						{assign var=discount value=($listing.item_price * $listing.item_discount / 100)}
					{/if}

					<span class="label label-disabled">{$core.config.coupon_item_price_currency}{$listing.item_price}</span>
					<span class="label label-success">{$core.config.coupon_item_price_currency}{$discount_total|string_format:"%.2f"}</span>
					<span class="label-saving">{lang key='you_save'} {$core.config.coupon_item_price_currency}{$discount|string_format:"%.2f"}</span>
				{else}
					<span class="label label-warning">{$core.config.coupon_item_price_currency}{$listing.item_price}</span>
				{/if}
			</div>
		{/if}

		{assign randId 1|rand:20000}
		{if $listing.expire_date != 0}
			<div class="coupon-expire text-error">
				<i class="icon-time"></i> 
				<span id="timer-{$randId}-{$listing.id}" title="{lang key='coupon_expire'} {$listing.expire_date|date_format:$core.config.date_format}"></span>
			</div>
		{/if}

		<div class="ia-item-body">{$listing.short_description|strip_tags|truncate:150:'...'}</div>
		<div class="coupon-tags">
			<i class="icon-tags"></i>
			{if $listing.coupon_tags}
				{lang key='coupon_tags'}: {$listing.coupon_tags|replace:',':', '}
			{else}
				{lang key='no_coupon_tags'}
			{/if}
		</div>
	</div>

	<div class="ia-item-panel">
		{if $listing.member_id}
			<div class="coupon-user pull-left">
				<i class="icon-user"></i> <a href="{$smarty.const.IA_URL}member/{$listing.account_username}.html">{$listing.account}</a>
			</div>
		{/if}

		{if $listing.category_parent_id > 0 && (!isset($category) || $category.parent_id > 1)}
			<div class="coupon-category pull-left">
				<i class="icon-folder-close"></i> <a href="{$core.packages.coupons.url}{$listing.category_alias}/">{$listing.category_title}</a>
			</div>
		{/if}

		{if $member && $member.id != $listing.member_id}
			<div class="pull-left">
				{printFavorites item=$listing itemtype='coupons'}
			</div>
		{/if}

		<div class="coupon-stats pull-right">{$listing.views_num} {lang key='views_since'} {$listing.date_added|date_format:$core.config.date_format}</div>
	</div>

</div>
{ia_add_js}
$(function () {
	$('#timer-{$randId}-{$listing.id}').countdown(
	{
		date: '{$listing.expire_date|date_format:$core.config.date_format}',
		htmlTemplate: "%dd %hh %im %ss left"
	});

	$('#coupon-list-{$listing.id} h4.media-heading a:first').on('click', function(e)
	{
		e.preventDefault();

		var affiliateLink = $('#coupon-list-{$listing.id}').data('affiliate-link');
		var couponLink    = '{ia_url type='url' item='coupons' data=$listing}';

		if ('undefined' != typeof affiliateLink && '' != affiliateLink)
		{
			window.location.href = couponLink;
			window.open(affiliateLink, '_blank');
		}
		else
		{
			window.location.href = couponLink;
		}
	});
});
{/ia_add_js}