<div id="coupon-list-{$coupon.id}" class="media ia-item ia-item-bordered ia-item-coupon{if $coupon.featured} ia-item-featured{/if}{if $coupon.sponsored} ia-item-sponsored{/if}">
	{if $coupon.featured}
		<span class="ia-badge ia-badge-featured" title="{lang key='featured'}"><i class="icon-star"></i></span>
	{/if}

	{if $coupon.sponsored}
		<span class="ia-badge ia-badge-sponsored" title="{lang key='sponsored'}"><i class="icon-dollar"></i></span>
	{/if}

	<div class="pull-left">
		{if $coupon.shop_image}
			<a href="{printImage imgfile=$coupon.shop_image.path url=true fullimage=true}" class="ia-item-thumbnail" rel="ia_lightbox">
				{printImage imgfile=$coupon.shop_image.path title=$coupon.shop_title|escape:'html' class='media-object'}
			</a>
		{else}
			<a href="{$smarty.const.IA_URL}shop/{$coupon.shop_alias}.html" class="ia-item-thumbnail">
				<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$coupon.shop_website}" alt="Generated by WebThumbnail.org" class="media-object">
			</a>
		{/if}

		<div class="coupon-rate text-center">
			<a href="#" class="thumbs-up" data-id="{$coupon.id}" data-trigger="up"><i class="fa fa-thumbs-up fa-white"></i></a>
			<span class="rate good" id="thumb_result_{$coupon.id}">{$coupon.thumbs_num|default:0}</span>
			<a href="#" class="thumbs-down" data-id="{$coupon.id}" data-trigger="down"><i class="fa fa-thumbs-down fa-white"></i></a>
		</div>
	</div>

	<div class="media-body">
		<h4 class="media-heading">{ia_url type='link' item='coupons' data=$coupon text=$coupon.title} <small>{lang key='from'} <a href="{$smarty.const.IA_URL}shop/{$coupon.shop_alias}.html">{$coupon.shop_title}</a></small></h4>

		{if $coupon.item_price && '0.00' != $coupon.item_price}
			<div class="coupon-price clearfix">
				{if $coupon.item_discount}
					{if 'fixed' == $coupon.item_discount_type}
						{assign var=discount_total value=($coupon.item_price - $coupon.item_discount)}
						{assign discount $coupon.item_discount}
					{else}
						{assign var=discount_total value=($coupon.item_price - $coupon.item_price * $coupon.item_discount / 100)}
						{assign var=discount value=($coupon.item_price * $coupon.item_discount / 100)}
					{/if}

					<span class="label label-disabled">{$core.config.coupon_item_price_currency}{$coupon.item_price}</span>
					<span class="label label-success">{$core.config.coupon_item_price_currency}{$discount_total|string_format:"%.2f"}</span>
					<span class="label-saving">{lang key='you_save'} {$core.config.coupon_item_price_currency}{$discount|string_format:"%.2f"}</span>
				{else}
					<span class="label label-warning">{$core.config.coupon_item_price_currency}{$coupon.item_price}</span>
				{/if}
			</div>
		{/if}

		{if $core.config.purchase_coupon_codes}
			{coupon_code coupon=$coupon}
		{elseif $core.config.hide_coupon_code}
			<div class="coupon-code coupon-code--hidden">
				<a href="{if $coupon.affiliate_link && 'http://' != $coupon.affiliate_link}{$coupon.affiliate_link}{elseif $coupon.shop_affiliate_link && 'http://' != $coupon.shop_affiliate_link}{$coupon.shop_affiliate_link}{else}#{/if}" target="_blank">{lang key='show_coupon_code'}</a>
				<span>{$coupon.coupon_code}</span>
			</div>
		{else}
			<div class="coupon-code">
				{$coupon.coupon_code}
				<div id="clip_{$coupon.id}" class="code-copy clip_{$coupon.id}" data-clipboard-text="{$coupon.coupon_code}" title="{lang key='coupon_copy_to_clipboard'}" data-affiliate-link="{if $coupon.affiliate_link && 'http://' != $coupon.affiliate_link}{$coupon.affiliate_link}{elseif $coupon.shop_affiliate_link && 'http://' != $coupon.shop_affiliate_link}{$coupon.shop_affiliate_link}{/if}" data-coupon-link="{ia_url type='url' item='coupons' data=$coupon}"></div>
			</div>
		{/if}

		{assign randId 1|rand:20000}
		{if $coupon.expire_date != 0}
			<div class="coupon-expire text-error">
				<i class="icon-time"></i> 
				<span id="timer-{$randId}-{$coupon.id}" title="{lang key='coupon_expire'} {$coupon.expire_date|date_format:$core.config.date_format}"></span>
			</div>
		{/if}

		<div class="ia-item-body">{$coupon.short_description|strip_tags|truncate:150:'...'}</div>
		<div class="coupon-tags">
			<i class="icon-tags"></i>
			{if $coupon.coupon_tags}
				{lang key='coupon_tags'}: {$coupon.coupon_tags|replace:',':', '}
			{else}
				{lang key='no_coupon_tags'}
			{/if}
		</div>
	</div>

	<div class="ia-item-panel">
		{if $coupon.member_id}
			<div class="coupon-user pull-left">
				<i class="icon-user"></i> <a href="{$smarty.const.IA_URL}member/{$coupon.account_username}.html">{$coupon.account}</a>
			</div>
		{/if}

		{if $coupon.category_parent_id > 0 && (!isset($category) || $category.parent_id > 1)}
			<div class="coupon-category pull-left">
				<i class="icon-folder-close"></i> <a href="{$packages.coupons.url}{$coupon.category_alias}/">{$coupon.category_title}</a>
			</div>
		{/if}

		{if $member && $member.id != $coupon.member_id}
			<div class="pull-left">
				{printFavorites item=$coupon itemtype='coupons'}
			</div>
		{/if}

		<div class="coupon-stats pull-right">{$coupon.views_num} {lang key='views_since'} {$coupon.date_added|date_format:$core.config.date_format}</div>
	</div>

</div>
{ia_add_js}
$(function()
{
	$('#timer-{$randId}-{$coupon.id}').countdown(
	{
		date: '{$coupon.expire_date|date_format:$core.config.date_format}',
		htmlTemplate: "%dd %hh %im %ss left"
	});

	var clip_{$coupon.id} = new ZeroClipboard($('.clip_{$coupon.id}'),
	{
		moviePath: '{$smarty.const.IA_CLEAR_URL}js/utils/zeroclipboard/ZeroClipboard.swf',
		hoverClass: 'hover',
		activeClass: 'active'
	});

	clip_{$coupon.id}.on('complete', function(client, args)
	{
		var affiliateLink = $(this).data('affiliate-link');
		var couponLink    = $(this).data('coupon-link');
		
		if ('undefined' != typeof affiliateLink && '' != affiliateLink)
		{
			window.location.href = couponLink;
			window.open(affiliateLink, '_blank');
		}
		else
		{
			window.location.href = couponLink;
		}
	});
});
{/ia_add_js}

{if $core.config.hide_coupon_code}
	{ia_add_js}
$(function () {
	$('#coupon-list-{$coupon.id} .coupon-code--hidden > a').on('click', function(e)
	{
		if ('#' === $(this).attr('href'))
		{
			e.preventDefault();
		}
		
		$(this).hide().next().show();
	});
});
	{/ia_add_js}
{/if}