<div class="ia-item ia-item--border ia-item--coupon{if $coupon.featured} ia-item---featured{/if}{if $coupon.sponsored} ia-item--sponsored{/if} has-panel" id="coupon-list-{$coupon.id}">
	<div class="ia-item__image">
		{if $coupon.shop_image}
			<a href="{printImage imgfile=$coupon.shop_image.path url=true fullimage=true}" rel="ia_lightbox">
				{printImage imgfile=$coupon.shop_image.path title=$coupon.shop_title|escape:'html' class='img-responsive'}
			</a>
		{else}
			<a href="{$smarty.const.IA_URL}shop/{$coupon.shop_alias}.html">
				<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$coupon.shop_website}" alt="Generated by WebThumbnail.org" class="img-responsive">
			</a>
		{/if}

		<div class="coupon-rate text-center">
			<a href="#" class="thumbs-up" data-id="{$coupon.id}" data-trigger="up"><i class="fa fa-thumbs-up"></i></a>
			<span class="rate good" id="thumb_result_{$coupon.id}">{$coupon.thumbs_num|default:0}</span>
			<a href="#" class="thumbs-down" data-id="{$coupon.id}" data-trigger="down"><i class="fa fa-thumbs-down"></i></a>
		</div>
	</div>

	<div class="ia-item__labels">
		{if $coupon.sponsored}<span class="label label-warning" title="{lang key='sponsored'}"><span class="fa fa-star"></span> {lang key='sponsored'}</span>{/if}
		{if $coupon.featured}<span class="label label-info" title="{lang key='featured'}"><span class="fa fa-star-o"></span> {lang key='featured'}</span>{/if}
	</div>

	<div class="ia-item__content">
		<div class="ia-item__actions">
			{printFavorites item=$coupon itemtype='coupons' guests=true}
			{accountActions item=$coupon itemtype='coupons'}
		</div>

		<div class="ia-item__title">
			{ia_url type='link' item='coupons' data=$coupon text=$coupon.title} <small>{lang key='from'} <a href="{$smarty.const.IA_URL}shop/{$coupon.shop_alias}.html">{$coupon.shop_title}</a></small>
		</div>

		{if $coupon.item_price && '0.00' != $coupon.item_price}
			<div class="coupon-price clearfix">
				{if $coupon.item_discount}
					{if 'fixed' == $coupon.item_discount_type}
						{assign var=discount_total value=($coupon.item_price - $coupon.item_discount)}
						{assign discount $coupon.item_discount}
					{else}
						{assign var=discount_total value=($coupon.item_price - $coupon.item_price * $coupon.item_discount / 100)}
						{assign var=discount value=($coupon.item_price * $coupon.item_discount / 100)}
					{/if}

					<span class="label label-disabled">{$core.config.coupon_item_price_currency}{$coupon.item_price}</span>
					<span class="label label-success">{$core.config.coupon_item_price_currency}{$discount_total|string_format:"%.2f"}</span>
					<span class="label-saving">{lang key='you_save'} {$core.config.coupon_item_price_currency}{$discount|string_format:"%.2f"}</span>
				{else}
					<span class="label label-warning">{$core.config.coupon_item_price_currency}{$coupon.item_price}</span>
				{/if}
			</div>
		{/if}

		{if $core.config.purchase_coupon_codes}
			{coupon_code coupon=$coupon}
		{elseif $core.config.hide_coupon_code}
			<div class="coupon-code coupon-code--hidden">
				<a href="{if $coupon.affiliate_link && 'http://' != $coupon.affiliate_link}{$coupon.affiliate_link}{elseif $coupon.shop_affiliate_link && 'http://' != $coupon.shop_affiliate_link}{$coupon.shop_affiliate_link}{else}#{/if}" target="_blank">{lang key='show_coupon_code'}</a>
				<span>{$coupon.coupon_code}</span>
			</div>
		{else}
			<div class="coupon-code">
				{$coupon.coupon_code}
				<div id="clip_{$coupon.id}" class="code-copy clip_{$coupon.id}" data-clipboard-text="{$coupon.coupon_code}" title="{lang key='coupon_copy_to_clipboard'}" data-affiliate-link="{if $coupon.affiliate_link && 'http://' != $coupon.affiliate_link}{$coupon.affiliate_link}{elseif $coupon.shop_affiliate_link && 'http://' != $coupon.shop_affiliate_link}{$coupon.shop_affiliate_link}{/if}" data-coupon-link="{ia_url type='url' item='coupons' data=$coupon}"></div>
			</div>
		{/if}

		{assign randId 1|rand:20000}
		{if $coupon.expire_date != 0}
			<div class="coupon-expire text-danger">
				<span class="fa fa-clock-o"></span> 
				<span id="timer-{$randId}-{$coupon.id}" title="{lang key='coupon_expire'} {$coupon.expire_date|date_format:$core.config.date_format}"></span>
			</div>
		{/if}

		<p>{$coupon.short_description|strip_tags|truncate:150:'...'}</p>

		<p class="coupon-tags text-fade-50">
			<span class="fa fa-tags"></span>
			{if $coupon.coupon_tags}
				{lang key='coupon_tags'}: {$coupon.coupon_tags|replace:',':', '}
			{else}
				{lang key='no_coupon_tags'}
			{/if}
		</p>
	</div>

	<div class="ia-item__panel">
		{if $coupon.member_id}
			<span class="ia-item__panel__item pull-left">
				<span class="fa fa-user"></span> <a href="{$smarty.const.IA_URL}member/{$coupon.account_username}.html">{$coupon.account}</a>
			</span>
		{/if}

		{if $coupon.category_parent_id > 0 && (!isset($category) || $category.parent_id > 1)}
			<span class="ia-item__panel__item pull-left">
				<span class="fa fa-folder-o"></span> <a href="{$core.packages.coupons.url}{$coupon.category_alias}/">{$coupon.category_title}</a>
			</span>
		{/if}

		<span class="ia-item__panel__item pull-right">
			{$coupon.views_num} {lang key='views_since'} {$coupon.date_added|date_format:$core.config.date_format}
		</span>
	</div>
</div>

{ia_add_js}
$(function()
{
	$('#timer-{$randId}-{$coupon.id}').countdown(
	{
		date: '{$coupon.expire_date|date_format:$core.config.date_format}',
		htmlTemplate: "%dd %hh %im %ss left"
	});

	var clip_{$coupon.id} = new ZeroClipboard($('.clip_{$coupon.id}'),
	{
		moviePath: '{$smarty.const.IA_CLEAR_URL}js/utils/zeroclipboard/ZeroClipboard.swf',
		hoverClass: 'hover',
		activeClass: 'active'
	});

	clip_{$coupon.id}.on('complete', function(client, args)
	{
		var affiliateLink = $(this).data('affiliate-link');
		var couponLink    = $(this).data('coupon-link');
		
		if ('undefined' != typeof affiliateLink && '' != affiliateLink)
		{
			window.location.href = couponLink;
			window.open(affiliateLink, '_blank');
		}
		else
		{
			window.location.href = couponLink;
		}
	});
});
{/ia_add_js}

{if $core.config.hide_coupon_code}
	{ia_add_js}
$(function () {
	$('#coupon-list-{$coupon.id} .coupon-code--hidden > a').on('click', function(e)
	{
		if ('#' === $(this).attr('href'))
		{
			e.preventDefault();
		}
		
		$(this).hide().next().show();
	});
});
	{/ia_add_js}
{/if}