<div class="shop-page clearfix">
	<div class="image pull-left">
		{if $shop.shop_image}
			<a href="{printImage imgfile=$shop.shop_image.path url=true type='full'}" class="shop-thumb" rel="ia_lightbox">
				{printImage imgfile=$shop.shop_image.path title=$shop.title|escape:'html'}
			</a>
		{else}
			<a href="{$shop.website}" class="shop-thumb" target="_blank">
				<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$shop.website}" alt="Generated by WebThumbnail.org">
			</a>
		{/if}
	</div>

	<p>
		<b>{lang key='website'}:</b> 
		{if $shop.affiliate_link && 'http://' != $shop.affiliate_link}
			<a href="{$shop.affiliate_link}" target="_blank">{$shop.website}</a>
		{else}
			<a href="{$shop.website}" target="_blank">{$shop.website}</a>
		{/if}
	</p>

	{if $shop.description}
		<div class="slogan">{$shop.description}</div>
	{/if}
</div>

{ia_hooker name='smartyViewListingBeforeFooter'}
<form>
	<select id="js-sort-options" name='sorting' class='form-control'>
		<option value="all"{if isset($smarty.get.sorting) && 'all' == $smarty.get.sorting} selected{/if}>{lang key='show_all_coupons'}</option>
		<option value="active"{if isset($smarty.get.sorting) && 'active' == $smarty.get.sorting} selected{/if}>{lang key='show_active_coupons'}</option>
		<option value="expired"{if isset($smarty.get.sorting) && 'expired' == $smarty.get.sorting} selected{/if}>{lang key='show_expired_coupons'}</option>
	</select>
</form>
{ia_add_js}
$(function()
{
	$('#js-sort-options').on('change', function()
	{
		$(this).parent().submit();
	});
});
{/ia_add_js}
<hr>
<h3>{lang key='coupons'}: {$coupons|count}</h3>

{if $coupons}
	{foreach $coupons as $listing}
		{include file='extra:coupons/list-coupons'}
	{/foreach}
{else}
	<div class="alert alert-info">{lang key='no_coupons_for_shop'}</div>
{/if}

{if $coupons_expired}
	<h3>{lang key='expired_coupons'}: {$coupons_expired|count}</h3>
	{foreach $coupons_expired as $listing}
		{include file='extra:coupons/list-coupons'}
	{/foreach}
{/if}