{if $letters}
	{include file='ia-alpha-sorting.tpl' letters=$letters url="{$core.packages.coupons.url}shops/"}
{/if}

{if !empty($shops)}
	{$letter=''}
	<div class="shops-list">
		{foreach $shops as $shop}
			{if $letter|upper != $shop.title[0]|upper}
				{if '' != $letter}</ul>{/if}
				<h2>{$shop.title[0]|upper}</h2>
				<hr>
			{/if}
			<div class="media ia-item ia-item-bordered shops-list-item">
				{if $shop.shop_image}
					<a href="{printImage imgfile=$shop.shop_image.path url=true fullimage=true}" class="pull-left ia-item-thumbnail" rel="ia_lightbox">
						{printImage imgfile=$shop.shop_image.path title=$shop.title|escape:'html' class='media-object'}
					</a>
				{else}
					<a href="{$smarty.const.IA_URL}shop/{$shop.title_alias}.html" class="pull-left ia-item-thumbnail">
						<img src="http://api.webthumbnail.org?width=150&height=150&format=png&screen=1024&url={$shop.website}" alt="Generated by WebThumbnail.org" class="media-object">
					</a>
				{/if}

				<div class="media-body">
					<h4 class="media-heading">{ia_url type='link' item='shops' data=$shop text=$shop.title}</h4>
					<div class="ia-item-body">{$shop.description|strip_tags|truncate:200:'...'}</div>
				</div>
			</div>
			{assign var=letter value=$shop.title[0]}
		{/foreach}
	</div>
{else}
	<div class="alert alert-info">{lang key='no_shops'}</div>
{/if}